# Copyright 2006 The Android Open Source Project

ifdef WIFI_DRIVER_MODULE_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_PATH=\"$(WIFI_DRIVER_MODULE_PATH)\"
endif
ifdef WIFI_DRIVER_MODULE_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_ARG=\"$(WIFI_DRIVER_MODULE_ARG)\"
endif
ifdef WIFI_DRIVER_MODULE_NAME
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_NAME=\"$(WIFI_DRIVER_MODULE_NAME)\"
endif
ifdef WIFI_FIRMWARE_LOADER
LOCAL_CFLAGS += -DWIFI_FIRMWARE_LOADER=\"$(WIFI_FIRMWARE_LOADER)\"
endif

ifdef WIFI_DRIVER_FW_PATH_STA
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_STA=\"$(WIFI_DRIVER_FW_PATH_STA)\"
endif
LOCAL_CFLAGS += -DWIFI_DRIVER_43241_FW_PATH_STA=\"$(WIFI_DRIVER_43241_FW_PATH_STA)\"
LOCAL_CFLAGS += -DWIFI_DRIVER_4334_FW_PATH_STA=\"$(WIFI_DRIVER_4334_FW_PATH_STA)\"
LOCAL_CFLAGS += -DWIFI_DRIVER_4335_FW_PATH_STA=\"$(WIFI_DRIVER_4335_FW_PATH_STA)\"

ifdef WIFI_DRIVER_FW_PATH_AP
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_AP=\"$(WIFI_DRIVER_FW_PATH_AP)\"
endif
LOCAL_CFLAGS += -DWIFI_DRIVER_43241_FW_PATH_AP=\"$(WIFI_DRIVER_43241_FW_PATH_AP)\"
LOCAL_CFLAGS += -DWIFI_DRIVER_4334_FW_PATH_AP=\"$(WIFI_DRIVER_4334_FW_PATH_AP)\"
LOCAL_CFLAGS += -DWIFI_DRIVER_4335_FW_PATH_AP=\"$(WIFI_DRIVER_4335_FW_PATH_AP)\"

ifdef WIFI_DRIVER_FW_PATH_P2P
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_P2P=\"$(WIFI_DRIVER_FW_PATH_P2P)\"
endif
LOCAL_CFLAGS += -DWIFI_DRIVER_43241_FW_PATH_P2P=\"$(WIFI_DRIVER_43241_FW_PATH_P2P)\"
LOCAL_CFLAGS += -DWIFI_DRIVER_4334_FW_PATH_P2P=\"$(WIFI_DRIVER_4334_FW_PATH_P2P)\"
LOCAL_CFLAGS += -DWIFI_DRIVER_4335_FW_PATH_P2P=\"$(WIFI_DRIVER_4335_FW_PATH_P2P)\"

ifdef WIFI_DRIVER_FW_PATH_PARAM
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_PARAM=\"$(WIFI_DRIVER_FW_PATH_PARAM)\"
endif

LOCAL_SRC_FILES += wifi/wifi.c

LOCAL_SHARED_LIBRARIES += libnetutils
